version: 2
updates:
  - package-ecosystem: cargo
    directory: "/netlify/functions/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"