[build]
  command = "npm run build && echo $DRAW_ID"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  framework = "vite"
  targetPort = 5173