on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build_and_test:
    name: Download release
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: 'jiep/lottery'
          fileName: '*'
          tag: 'v0.2.2'
          out-file-path: 'lottery'
          token: ${{ secrets.GITHUB_TOKEN }}
      - shell: bash
        run: |
          cd lottery
          unzip *.zip
          ./lottery find --number 44733 --json > ~/44733.json
          cd .. && rm lottery
    
      - name: Checkout repo
        uses: actions/checkout@v3

      - shell: bash
        run: |
          mv ~/44733.json public/data/44733.json

      - name: Push to GitHub
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add .
          git commit -m "Data updated"
          git push

    
              

  