on:
  schedule:
    - cron: "0 0 * 7-12 *"

jobs:
  build_and_test:
    name: Download release
    runs-on: ubuntu-latest
    outputs:
      changes_exist: ${{ steps.changes.outputs.changes_exist }}
    steps:
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: 'jiep/lottery'
          fileName: 'lottery-x86_64-unknown-linux-gnu.zip'
          tag: 'v0.2.2'
          out-file-path: 'lottery'
          token: ${{ secrets.GITHUB_TOKEN }}
      - shell: bash
        run: |
          cd lottery
          unzip *.zip
          ./lottery find --number 44733 --json > ~/44733.json
          cd .. && rm -rf lottery
    
      - name: Checkout repo
        uses: actions/checkout@v3

      - shell: bash
        run: |
          mv ~/44733.json public/data/44733.json

      - name: Check for changes
        id: changes
        run: |
          if git diff --exit-code; then
            echo "::set-output name=changes_exist::false"
          else
            echo "::set-output name=changes_exist::true"
          fi

      - name: Push to GitHub
        if: ${{ steps.changes.outputs.changes_exist == 'true' }}
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add .
          git commit -m "Data updated"
          git push

    
              

  